name: Build macOS App

on:
  workflow_dispatch:  # run manually from Actions tab
  push:
    tags:
      - 'v*'  # runs when you push a tag like v1.0

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pyinstaller

    - name: Build macOS app
      run: |
        pyinstaller --onefile --windowed main.py
        cd dist
        mv main.app Sortly.app
        zip -r Sortly-mac.zip Sortly.app

    - name: Upload build as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sortly-mac
        path: dist/Sortly-mac.zip
