name: Build macOS app (py2app)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"  # Match your project's version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        pip install -r requirements.txt  # If you have one

    - name: Build .app with py2app
      run: |
        python setup.py py2app

    - name: Zip the app
      run: |
        cd dist
        zip -r Sortly-mac.zip Sortly.app

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Sortly-mac
        path: dist/Sortly-mac.zip
